name: "nightly sanity test"
on:
  schedule:
    - cron:  '30 20 * * 1-5'

jobs:
  sanity:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [8, 11, 17]
        impl: [hotspot]
        buildlist: [openjdk, system, functional]
    steps:
    - uses: actions/checkout@v4
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: ${{ matrix.version }}
        targets: JDK_${{ matrix.version }}
        impl: ${{ matrix.impl }}
        source: 'nightly'
    - name: AQA
      uses: ./
      with: 
        version: ${{ matrix.version }}
        jdksource: 'install-jdk'
        build_list: ${{ matrix.buildlist}}
        target: '_sanity.regular'
