name: "nightly sanity test"
on:
  push:
    branches:
      - zdtsw/chore_2

jobs:
  sanity-on-nonwindows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [8, 11, 17]
        impl: [hotspot]
        buildlist: [openjdk, system, functional]
    steps:
    - uses: actions/checkout@v3
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: ${{ matrix.version }}
        targets: JDK_${{ matrix.version }}
        impl: ${{ matrix.impl }}
        source: 'nightly'
    - name: AQA
      uses: ./
      with: 
        version: ${{ matrix.version }}
        jdksource: 'install-jdk'
        build_list: ${{ matrix.buildlist}}
        target: '_sanity.regular'
  sanity-on-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        version: [8, 11, 17]
        impl: [hotspot]
        buildlist: [openjdk, system, functional]
    steps:
    - uses: actions/checkout@v3
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: ${{ matrix.version }}
        targets: JDK_${{ matrix.version }}
        impl: ${{ matrix.impl }}
        source: 'nightly'
    - name: AQA
      uses: ./
      with: 
        version: ${{ matrix.version }}
        jdksource: 'install-jdk'
        build_list: ${{ matrix.buildlist}}
        target: '_sanity.regular'
