name: "run-aqa build with push to master"
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  openjdk-on-windows: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
    - uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-20.04
    - uses: actions/checkout@v3
    - name: AQA
      uses: ./
      with: 
        version: '11'
        jdksource: 'github-hosted'
        build_list: 'openjdk'
        target: '_jdk_custom'