name: "run-aqa build with push to master"
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  system-on-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
    - uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-20.04
        additional-packages:
          ant
          make
    - uses: actions/checkout@v3
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '11'
        targets: 'JDK_11'
        impl: 'openj9'
        source: 'nightly'
    - name: AQA
      uses: ./
      with: 
        version: '11'
        jdksource: 'install-jdk'
        build_list: 'system'
        target: '_DaaLoadTest_daa1_5m'
        aqa-testsRepo: 'adoptium/aqa-tests:v0.9.0'