name: "run-aqa build with push to master"
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  openjdk: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: AQA
      uses: ./
      with: 
        version: '11'
        jdksource: 'github-hosted'
        build_list: 'openjdk'
        target: '_jdk_custom'
  openjdk_disto: # make sure build/ci work properly with other distros
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [adoptopenjdk/centos7_build_image, adoptopenjdk/alpine3_build_image]
    steps:
    - uses: actions/checkout@v4
    - name: AQA
      uses: ./
      with: 
        version: '8'
        jdksource: 'github-hosted'
        build_list: 'openjdk'
        target: '_jdk_custom'
  functional: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '11'
        targets: 'JDK_11'
        impl: 'openj9'
        source: 'nightly'
    - name: AQA
      uses: ./
      with: 
        version: '11'
        jdksource: 'install-jdk'
        build_list: 'functional'
        target: '_floatSanityTests'
  system: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '11'
        targets: 'JDK_11'
        impl: 'openj9'
        source: 'nightly'
    - name: AQA
      uses: ./
      with: 
        version: '11'
        jdksource: 'install-jdk'
        build_list: 'system'
        target: '_DaaLoadTest_daa1_5m'
